### ISSUE TITLE
Missing Debug implementation

### ISSUE THREAD

**Issue by imp** [sbstp/attohttpc#10]
Some important types are missing `Debug` implementation. `Debug` is considered essential and may be easily derived.

**Comment by imp** [comment]
Thanks! Any chance to cut a new drop with this fix? I wanted to replace `reqwest` with `attohttpc` in my project and it is too much work without `Debug`.

**Comment by sbstp** [comment]
Sure thing I'll do it right away!

**Comment by sbstp** [comment]
Alright it's in 0.5.1
