### ISSUE TITLE
Any way to handle each chunk separately?

### ISSUE THREAD

**Issue by George-Miao** [sbstp/attohttpc#112]
Is there any thing like [this](https://docs.rs/reqwest/0.11.6/reqwest/struct.Response.html#method.chunk) to get each chunk separately?

**Comment by sbstp** [comment]
The `Response` object implements the Read trait, so you can just read from it using whatever buffer size you like.

**Comment by George-Miao** [comment]
> The `Response` object implements the Read trait, so you can just read from it using whatever buffer size you like.

I see. However what if the chunk size isn't known? Is there anyway to know what's next chunk's size is or I have to implement my own chunk-encode logic?

**Comment by sbstp** [comment]
The chunk decoding logic is built-in the library, you won't see any of the chunked protocol in the data by reading from the response.

If you actually want to implement the chunk decoding yourself for whatever reason, I'm not sure if the library even allows this. You'd have to look at the code.

**Comment by George-Miao** [comment]
> The chunk decoding logic is built-in the library, you won't see any of the chunked protocol in the data by reading from the response.
> 
> 
> 
> If you actually want to implement the chunk decoding yourself for whatever reason, I'm not sure if the library even allows this. You'd have to look at the code.

Okay. Thanks for answering.
