### ISSUE TITLE
Support for `rustls-native-certs`

### ISSUE THREAD

**Issue by charlespierce** [sbstp/attohttpc#133]
Inspired by the `rustls-tls-native-roots` feature in [Reqwest](https://docs.rs/reqwest/latest/reqwest/#optional-features), would this project be open to a feature flag to enable pulling root certificates from the native store via [`rustls-native-certs`](https://crates.io/crates/rustls-native-certs/0.6.2)?

It's possible today to add them manually using the `add_root_certificate` method, however that adds a couple of complications: 

* The consumer needs to make sure to exactly match the `rustls-native-certs` version to the `rustls` version used transitively within `attohttpc`
* The consumer needs to create helpers to make sure that all requests go through a `RequestBuilder` that adds those certs.
* Some native stores hold old certs with invalid formats, which are rejected when they're added using `add_root_certificate` (see a comment in the [`reqwest` implementation](https://github.com/seanmonstar/reqwest/blob/231b18f83572836c674404b33cb1ca8b35ca3e36/src/async_impl/client.rs#L363-L365))

Having the ability to use the native store built in to attohttpc would alleviate all of these and allow consumers to opt-in easily via a feature flag.

I'm happy to take on creating a PR, if it's a feature you're open to adding.

**Comment by sbstp** [comment]
Yeah sure!
