### ISSUE TITLE
Add a method on Response for retrieving the final URL

### ISSUE THREAD

**Issue by baskerville** [sbstp/attohttpc#136]
It would seem that there's no equivalent to *reqwest*'s [`url`](https://docs.rs/reqwest/latest/reqwest/blocking/struct.Response.html#method.url) method on the `Response` type?

**Comment by sbstp** [comment]
I have no objection to adding it. Are you interested in creating a PR?

**Comment by baskerville** [comment]
> Are you interested in creating a PR?

Yes: #137.
