### ISSUE TITLE
Creating a POST request based on curl syntax

### ISSUE THREAD

**Issue by EvilWatermelon** [sbstp/attohttpc#146]
Hi,

I want to make a POST request from this curl request.
```
curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=diva-beta.apk&hash=82ab8b2193b3cfb1c737e3a786be363a" -H "Authorization:18d770e0013dedd4554f88c1404b752b47da966766045fed21e68e0b1669bf39"
```

I cannot figure out how `--data` has to be handled. Is this a Vector of params or a request body?

**Comment by adamreichold** [comment]
[cURL's `--data`](https://curl.se/docs/manpage.html#-d) posts the given content as `application/x-www-form-urlencoded`, so you most likely want to enable the `form` feature and use the [`RequestBuilder::form` method](https://docs.rs/attohttpc/latest/attohttpc/struct.RequestBuilder.html#method.form), e.g.

```rust
post("http://localhost:8000/api/v1/scan").form(&[("scan_type", "apk"), ("file_name", "diva-beta.apk"), ("hash", "82ab8b2193b3cfb1c737e3a786be363a")])
```

**Comment by EvilWatermelon** [comment]
Thanks, it worked.
