### ISSUE TITLE
Setting `Content-length` for a `multipart/form-data` request

### ISSUE THREAD

**Issue by mattvalleycodes** [sbstp/attohttpc#168]
Hi 

I was wondering if there is a built-in way to compute and set value of the `Content-length` header for a `multipart/form-data` request. I was looking at the implementation and I can see that [attohttpc](https://github.com/sbstp/attohttpc) is not setting the header.

**Comment by sbstp** [comment]
We're using the multipart library which is now deprecated. Not sure what the future holds for multipart support.
