### ISSUE TITLE
Name is not memorable

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#36]
The crate name is very hard to remember.

It also doesn't look like a name of a high-level HTTP client: if I saw it on crates.io I'd expect it to be some low-level implementation detail, not something I can use directly. For reference, other high-level clients are called something like "reqwest", "isahc", "ureq".

It might be a good idea to use a more memorable name for this crate, like "hytt" or "ht2p".

**Comment by adamreichold** [comment]
Fearing that this will turn into bike-shedding, I have to admit that I very much disagree. I found the name immediately memorable and satisfyingly comprehensible, i.e. atto-http-c a very small (atto as the SI prefix for 10^-18) HTTP client.

I'd also like to add that there is a significant cost to changing an existing name, so there should be a very good reason to do so.

**Comment by Shnatsel** [comment]
My science background bottoms out at "pico", so that name looked like alphabet soup to me.

FYI "isahc" was called "chttp" until [very recently](https://www.reddit.com/r/rust/comments/clpaah/chttp_http_client_has_been_officially_renamed_to/evx7lzp/).

**Comment by adamreichold** [comment]
> FYI "isahc" was called "chttp" until very recently.

Personally, I distinctly remember having a hard time remembering "isahc" and searching for "chttp" to find the crate after its renaming.

**Comment by sbstp** [comment]
I'm not that fond of the name. It's pretty generic and unoriginal. At first it was called lynx after the Canadian animal but there's a TUI web browser also named lynx, so it wasn't a good pick.

I personally am in favor of cargo namespacing so the damn thing could just be called "sbstp/request" or something similar but that's another debate.

The library has gained a decent amount of popularity under this name now so I'm inclined to leave it as is.

**Comment by adamreichold** [comment]
> The library has gained a decent amount of popularity under this name now so I'm inclined to leave it as is.

So let's close this for now?

**Comment by adamreichold** [comment]
@sbstp No further discussion here, so let's close?
