### ISSUE TITLE
Allow disabling certificate verification

### ISSUE THREAD

**Issue by tscs37** [sbstp/attohttpc#38]
For development purposes it can be useful to ignore certificate requirements (ie, expired certificates, mismatching hostnames, etc.)

It would be useful if the RequestBuilder had an option to disable Certificate Verification, something like `danger_allow_invalid_certificates()`.

**Comment by sbstp** [comment]
Yes this is a something I wanted to do. I think it can be easily done by adding a parameter to the RequestBuilder i.e. `attohttpc::get("https://localhost:8080").allow_insecure(true)`, something like this.

**Comment by sbstp** [comment]
This is out in 0.10.0
