### ISSUE TITLE
Support for IPv6 addresses

### ISSUE THREAD

**Issue by gh0st42** [sbstp/attohttpc#53]
While switching my code from IPv4 only to mixed mode as well as IPv6 only mode, I encountered a strange bug in *attohttpc*.

At first, I thought it would be as easy as replacing strings such as *"http://127.0.0.1:3000/fancy_rest"* with *"http://[::1]:3000/fancy_rest"*. The latter works in my browser and in `curl`. Even the `url` crate can parse it [correctly](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=025db104ed5330d728b9c7752c473333). 

Just when I use `attohttpc` I get the following error on Linux:
```
Error(Io(Custom { kind: Other, error: "failed to lookup address information: Name or service not known" }))
```
on other systems it might also be displayed like the following:
```
Error(Io(Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" })) 
```

Probably trying to interpret *[::1]* as a hostname instead of an `IpAddr`.

Unfortunately, `attohttpc` is not yet available on the rust playground, otherwise, I would have shown a minimal example there.

And totally unrelated: thank you for providing a pretty neat, slim and efficient http client library without async+await :D

**Comment by adamreichold** [comment]
I think the problem is that `Ipv6Addr::from_str` [does not parse]() the `[...]` notation, but we use `Url::host_str` which hands out this notation instead of using `Url::host` which gives either an already parsed address or a domain name. Will prepare an MR to switch us to `Url::host`...
