### ISSUE TITLE
Support streaming request bodies

### ISSUE THREAD

**Issue by sfackler** [sbstp/attohttpc#55]
It'd be nice if there were a way to send a request body without needing to buffer the entire thing in memory first.

**Comment by adamreichold** [comment]
@sbstp What do you think of porting zeptohttpc's [`BodyWriter`](https://github.com/adamreichold/zeptohttpc/blob/master/src/body_writer.rs) trait here?

**Comment by sbstp** [comment]
@adamreichold looks like a good idea.

**Comment by sbstp** [comment]
Could we support streaming bodies for non Seek streams also? Just use like the CompressedBody does.

**Comment by adamreichold** [comment]
> Could we support streaming bodies for non Seek streams also? Just use like the CompressedBody does.

AFAIU the problem for pure `Read` bodies is that with redirects, one might need to produce the body multiple times and hence the need to rewind. `CompressedBody` is just a wrapper that relies on the inner body to rewind and `JsonBody` does not consume the actual value that is written.

I see two alternatives here:
* The body is able to indicate whether it can rewind or not and redirects just fail if the body was already consumed but that seems rather brittle to me.
* We provide an implementation based on `F: Fn() -> R where R: Read` in stead of `R: Read`, i.e. a body that can produce a new readable stream every time but that might end up being more complicated than just letting the user reimplement `BodyWriter` directly.

**Comment by sbstp** [comment]
We should look at the HTTP semantics for this. I think we could implement the Expect-Continue mechanism to solve this elegantly.

**Comment by adamreichold** [comment]
> We should look at the HTTP semantics for this. I think we could implement the Expect-Continue mechanism to solve this elegantly.

For a conforming server implementation, yes. More home-grown server implementations may wait for the body before producing the redirect response. But personally, I am not sure how relevant those are and if we should invest any effort into automatic downgrading.

But more generally speaking, do you have a use case in mind where we have a pure `Read` body that can only be consumed once? File contents and JSON values are possible without this. The client part of a proxy implementation would be the only thing I can come up with right now and I am not sure attohttpc would be a good choice for that.

**Comment by sbstp** [comment]
It would be a nice to have, but it's certainly not a blocker for this to land. We can start small and figure out later how to add it if someone asks for it.

**Comment by adamreichold** [comment]
Also the following part of the specification could be read like us need to be able to produce a body in any case.

> A client that receives a 417 (Expectation Failed) status code in response to a request containing a 100-continue expectation SHOULD repeat that request without a 100-continue expectation, since the 417 response merely indicates that the response chain does not support expectations (e.g., it passes through an HTTP/1.0 server).

However, there is also another take on this: Reduce POST requests with body to GET requests without one upon redirects which is what partly what reqwest is doing, e.g. https://github.com/seanmonstar/reqwest/blob/c81eb4ec411ab84eb16a143a39894bcce2e59d19/src/async_impl/client.rs#L1313 and https://github.com/seanmonstar/reqwest/blob/c81eb4ec411ab84eb16a143a39894bcce2e59d19/tests/redirect.rs#L6

My understanding is that this assumes that the body will always be consumed at the original location and only the response will be found elsewhere. But even reqwest seems to have `body::Inner::Reusable` and `body::Inner::Streaming` types to handle temporary or permanent redirects using fully buffered bodies.

> It would be a nice to have, but it's certainly not a blocker for this to land. We can start small and figure out later how to add it if someone asks for it.

I will try to wire something together that is minimally intrusive over the weekend if that is alright with you. Of course, feel free to go ahead if you have spare time available before that.

**Comment by sbstp** [comment]
I don't really have time to work on attohttpc this weekend, I have to work on my other project (kubie).

**Comment by adamreichold** [comment]
@sfackler You should be able to stream request bodies using the current `master` branch by implementing the `attohttpc::body::Body` trait and returning `attohttpc::body::BodyKind::Chunked` from the `attohttpc::body::Body::kind` method. Note that for now, this implies that your stream needs to be "rewindable" (or you can just panic when asked to write out the second time if you know there will be no redirects involved).

**Comment by sbstp** [comment]
We should probably mention in the docs of the write method that it might be called multiple times when redirects occur.

**Comment by adamreichold** [comment]
> We should probably mention in the docs of the write method that it might be called multiple times when redirects occur.

Will add another PR to do so.
