### ISSUE TITLE
Add helper for converting Response into Result based on StatusCode

### ISSUE THREAD

**Issue by imp** [sbstp/attohttpc#56]
When `Response` is received it can be checked for success using `is_success()` method in order to decide on further processing. It may be very helpful to provide a method that will convert `Response` into `Result<Response>` based on the the `StatusCode`.

Other HTTP client libraries provide similar facilities and they are very handy.
For example Python `requests` has [`raise_for_status`](https://requests.readthedocs.io/en/master/api/#requests.Response.raise_for_status) and `reqwest` has [`error_for_status`](https://docs.rs/reqwest/0.10.4/reqwest/struct.Response.html#method.error_for_status).

What do you think?

**Comment by sbstp** [comment]
Hey, this is out in `0.13.0`
