### ISSUE TITLE
Is Response::reader supposed to be awkward to get?

### ISSUE THREAD

**Issue by octylFractal** [sbstp/attohttpc#79]
I have code that uses the `Read` trait to stream the response data, but in order to get that for this library I had to jump through `Request::split`: `request.split().2`. Is there a reason that a simple `Request::reader()` isn't exposed?

**Comment by sbstp** [comment]
Kinda. The reason why you have to do this, is because the methods like `text_reader` consume the response.

I think Read could be implemented on the response though and it's just going to return EOF when the response has already been fully read.

**Comment by sbstp** [comment]
Added Read on the Response object.

**Comment by octylFractal** [comment]
That works for me, thanks!
