### ISSUE TITLE
Timeout not honored (program hang?) on some websites

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#85]
On 16 websites of the top million, `attohttpc` with 10-second connect timeout and 30-second full timeout does not complete the request in 60 seconds.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/main/attohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [attohttpc-hangs.tar.gz](https://github.com/sbstp/attohttpc/files/5933498/attohttpc-hangs.tar.gz)

ureq [has the same issue](https://github.com/algesten/ureq/issues/312), and the author has noticed that some of the affected websites have very long redirect chains. It is possible that the full request timeout is reset on every HTTP redirection.

**Comment by adamreichold** [comment]
Yes, the timeout is currently reset on every connection attempt, i.e. after each redirect.
