### ISSUE TITLE
Fetching google.com without 'charsets' feature fails; works in other clients

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#87]
Fetching google.com without enabling `charsets` feature fails with error: `Io Error: stream did not contain valid UTF-8`

This is strange because this works fine in e.g. `ureq` without charsets support and encoding_rs dependency not being present in the tree at all.

Code used for tests: https://github.com/Shnatsel/rust-http-clients-smoke-test
In the repository both clients have encoding support enabled; I've manually disabled it prior to this test.

**Comment by adamreichold** [comment]
From a first look, it seems like what we fetch from `http://www.google.com` does indeed contain invalid UTF-8
```
> isutf8 body 
body: line 8, char 2199, byte 7944: Expecting bytes in the following ranges: 00..7F C2..F4.
```
but `encoding_rs` seems to handle it.

**Comment by adamreichold** [comment]
This works in `ureq` because it uses the lossy conversion function:
```rust
        #[cfg(not(feature = "charset"))]
        {
            let mut buf: Vec<u8> = vec![];
            self.into_reader().read_to_end(&mut buf)?;
            Ok(String::from_utf8_lossy(&buf).to_string())
        }
```

That this works using `encoding_rs` is due to `encoding_rs_io::DecodeReaderBytes` calling `decode_to_utf8` instead of `decode_to_utf8_without_replacement`.

Of course, this still does not the invalid UTF-8 in the first place. 

@sbstp Was the choice of the strict conversion in `text_utf8` a deliberate choice? Do we want to revisit this or provide an alternative? Consistent between the functionality between the library with and without `encoding_rs` might be an argument? (Manually using the response as `std::io::Read` is of course possible, just not convenient.)

**Comment by adamreichold** [comment]
Just wanted to add that one downside of the above implementation is that it will copy the whole body even if it already is valid UTF-8 due to `String::from_utf8_lossy` not taking ownership of `buf`, so something more involved like
```rust
let buf = String::from_utf(buf).unwrap_or_else(|err| String::from_utf8_lossy(err.as_bytes()).to_owned());
```
should probably be used instead.

**Comment by adamreichold** [comment]
> Of course, this still does not explain the invalid UTF-8 in the first place.

Just to make sure this is not an error in our lower levels, I tried that using cURL and the issue of invalid UTF-8 in a response explicitly marked as UTF-8 is present:
```
> curl -obody -s http://www.google.com
> isutf8 body 
body: line 8, char 2199, byte 7929: Expecting bytes in the following ranges: 00..7F C2..F4.
```

**Comment by sbstp** [comment]
I'm guessing google encode their pages in ISO-8859-1 by default for compatibility reasons. We could try adding the [Accept-Charset](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset) header to indicate which charsets we support. Google probably supports this header, but I'm guessing most websites don't.

Using the lossy conversion is probably a good idea if we want to produce fewer errors. We should add a clear warning in the docs about the fact that it can be lossy though.

It would be preferable that this lossy behavior is matched when the charsets feature is enabled.

**Comment by adamreichold** [comment]
> I'm guessing google encode their pages in ISO-8859-1 by default for compatibility reasons. We could try adding the Accept-Charset header to indicate which charsets we support. Google probably supports this header, but I'm guessing most websites don't.

What puzzles me about this is that the response does contain
```html
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
```

> We should add a clear warning in the docs about the fact that it can be lossy though.

Will amend #88 

> It would be preferable that this lossy behavior is matched when the charsets feature is enabled.

This is already the case as we use `encoding_rs_io` which does _not_ call the `decode_to_utf8_without_replacement` variants of the decoding functions.

**Comment by adamreichold** [comment]
> We could try adding the Accept-Charset header to indicate which charsets we support.

This does not seem to change things:
```
> curl -obody -s -H "Accept-Chartset: utf-8" http://www.google.com
> isutf8 body 
body: line 8, char 2199, byte 7960: Expecting bytes in the following ranges: 00..7F C2..F4.
```
