### ISSUE TITLE
"invalid chunk size" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#91]
When querying some websites, such as http://movie-japan.com, attohttpc fails with the following error:

> Io Error: InvalidResponse: invalid chunk size

176 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/main/attohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [atto-invalid-chunk-size.tar.gz](https://github.com/sbstp/attohttpc/files/5990709/atto-invalid-chunk-size.tar.gz)

**Comment by Shnatsel** [comment]
Firefox and curl work fine.

**Comment by adamreichold** [comment]
At least for http://movie-japan.com, this is our less-than-principled chunk size parser not trimming whitespace before parsing into an integer, c.f. #98
