### ISSUE TITLE
"Http Error: invalid HTTP header name" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#92]
On some websites, e.g. http://hk-bbc.com, attohttpc fails with the following error:

> Http Error: invalid HTTP header name

Firefox and curl work fine.

96 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/main/attohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [atto-invalid-header-name.tar.gz](https://github.com/sbstp/attohttpc/files/5990742/atto-invalid-header-name.tar.gz)

**Comment by adamreichold** [comment]
Hhhmmm, the above site contains the following "header":
```
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php//usr/lib/php/modules/mcrypt.so' - /usr/local/php5/lib/php//usr/lib/php/modules/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0, PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php//usr/local/php5/lib/php/libmcrypt.so' - /usr/local/php5/lib/php//usr/local/php5/lib/php/libmcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0
```
which is not conformant AFAIU due to the space in "PHP Warning:" which is why
```rust
HeaderName::from_bytes(header)
```
fails.

#96 contains a possible fix but I am not very enthusiastic about doing this. But then again, the adage goes "be lenient in what you accept, but strict in what you produce".
